### PR TITLE
Removed skipping trigger if triggered commit belongs to multiple branches

### PR DESCRIPTION
**Pull request by auriusbendikas**
Hi @jmecosta,

I have removed the code that skips triggering build if changed commit is part of multiple branches.

I have performed extensive testing with the following build triggers:
```JavaScript
{
  "9baa11c5-43c6-4503-bb89-4c920f6de2d9": {
    "regexp": "refs/heads/(feature/.*)",
    "targetId": "tproj_Feature",
    "target": "build",
    "triggerOnPullRequest": "false",
    "cancelRunningBuilds": "false",
    "downStreamTriggerType": "build",
    "downStreamUrl": ""
  },
  "b2504b72-8b6d-4ec8-8318-5a7b256ace60": {
    "regexp": "refs/heads/(bugfix/.*)",
    "targetId": "tproj_Bugfix",
    "target": "build",
    "triggerOnPullRequest": "false",
    "cancelRunningBuilds": "false",
    "downStreamTriggerType": "build",
    "downStreamUrl": ""
  },
  "a8bd765e-8018-47ff-a9bd-fa5cb6d5b4be": {
    "regexp": "refs/tags/(.*)",
    "targetId": "tproj_Tags",
    "target": "build",
    "triggerOnPullRequest": "false",
    "cancelRunningBuilds": "false",
    "downStreamTriggerType": "build",
    "downStreamUrl": ""
  },
  "beb110ff-a6bc-414c-af32-5726a3292123": {
    "regexp": "refs/heads/(hotfix/.*)",
    "targetId": "tproj_Hotfix",
    "target": "build",
    "triggerOnPullRequest": "false",
    "cancelRunningBuilds": "false",
    "downStreamTriggerType": "build",
    "downStreamUrl": ""
  },
  "1684686e-f5a3-4afe-9478-b32a69881478": {
    "regexp": "refs/heads/(master)",
    "targetId": "tproj_Master",
    "target": "build",
    "triggerOnPullRequest": "false",
    "cancelRunningBuilds": "false",
    "downStreamTriggerType": "build",
    "downStreamUrl": ""
  },
  "a8f5d2a7-4715-4382-8208-cec2ce18116e": {
    "regexp": "refs/heads/(release/.*)",
    "targetId": "tproj_Release",
    "target": "build",
    "triggerOnPullRequest": "false",
    "cancelRunningBuilds": "false",
    "downStreamTriggerType": "build",
    "downStreamUrl": ""
  },
  "fa074a3b-837a-4514-88c6-345fe776bfd1": {
    "regexp": "refs/heads/(feature/.*)",
    "targetId": "tproj_FeaturePull",
    "target": "build",
    "triggerOnPullRequest": "true",
    "cancelRunningBuilds": "false",
    "downStreamTriggerType": "build",
    "downStreamUrl": ""
  },
  "1d4384e2-b2e5-4f52-8d85-2370e304d098": {
    "regexp": "refs/heads/(bugfix/.*)",
    "targetId": "tproj_BugfixPull",
    "target": "build",
    "triggerOnPullRequest": "true",
    "cancelRunningBuilds": "false",
    "downStreamTriggerType": "build",
    "downStreamUrl": ""
  },
  "0dbf3cdc-9404-4f42-87ae-f987464869dd": {
    "regexp": "refs/heads/(hotfix/.*)",
    "targetId": "tproj_HotfixPull",
    "target": "build",
    "triggerOnPullRequest": "true",
    "cancelRunningBuilds": "false",
    "downStreamTriggerType": "build",
    "downStreamUrl": ""
  },
  "c7829b81-4e7b-4272-a3a8-9059bf2d6a16": {
    "regexp": "refs/heads/(release/.*)",
    "targetId": "tproj_ReleasePull",
    "target": "build",
    "triggerOnPullRequest": "true",
    "cancelRunningBuilds": "false",
    "downStreamTriggerType": "build",
    "downStreamUrl": ""
  },
  "a806bfb5-4966-4ed4-964a-37a256cdd90a": {
    "regexp": "refs/tags/(.*)",
    "targetId": "tproj_TagsPull",
    "target": "build",
    "triggerOnPullRequest": "true",
    "cancelRunningBuilds": "false",
    "downStreamTriggerType": "build",
    "downStreamUrl": ""
  }
}
```
Following build configurations.

image

I have performed merging to master with pull requests open on all branches. Also merging from master to branch. Then branch rebasing and interactive branch rebasing of commits that are part of every branch. Also tested normal merges and squash merges.

And everything works as expected!!

But if fixes two important issues:

1. **Triggering on tag creation now works properly.**
0. **Now build is triggered when branch is created. Witch was a big problem in our project since we always had to push one fake commit in order to force trigger the build on new "empty" branch.**

### CODE REVIEW

**Comment by jmecosta** [comment]
2. so likely this is the reason. since we dont want builds if someone created a branch. because it makes no sense to just build something that has been build. Basically you will not be able to merge this branch anyway.  i rememenber that people were creating loads of those from Jira side, and basically TeamCity was just stuff building branches without any changes.

as far as i remember, this is default behaviour also if you just use teamcity with vcs triggers. 

- can you give a bit more reasoning why would you want to have branch build wihtout commits? the tags i can understand (more or less) if you take the tag to use that information during the build. but for empty branchs i think its just wast on build time in teamcity side

**Comment by jmecosta** [comment]
@auriusbendikas i suggest a new flag under advanced properties. the default can be build everything. i can disable this from my side.

**Comment by auriusbendikas** [comment]
@jmecosta,

Good to know. Will implement this as a config option! :+1:

**Comment by auriusbendikas** [comment]
Hi @jmecosta,

Moved the code that checks if branch is "empty" back. And added new option to "Trigger on Empty branches".

Tomorrow planning to work on UI. Feels like it needs more work. 😃 

image

**Comment by jmecosta** [comment]
Yep did not had patience to fight with css. I will review this and merge
tonight

**Comment by auriusbendikas** [comment]
@jmecosta 

Also sorry about so many unnecessary changes. I have saving rules enabled in my eclipse. Every time I save it applies those rules on the code.

**Comment by jmecosta** [comment]
yep, it would be nice if not formatiing anything on the code when doing those. later we can fix the code. but makes it easier to review

**Pull request merged**
