### PR TITLE
PR info passed to TeamCity build

### PR DESCRIPTION
**Pull request by ivan1767p**
PR info passed to TeamCity build.
parameters

### CODE REVIEW

**Comment by jmecosta** [comment]
Thanks for the pull request, usefully feature

**Comment by nekrasovweb** [comment]
Hello, useful functionality. When is the release build?

**Comment by jmecosta** [comment]
Today or tomorrow

**Comment by jmecosta** [comment]
@nekrasovweb @ivan1767p can u test this in version 4.10.1, ive run locally but couldnt get those to work. maybe something went wrong with some merge conflicts.

**Comment by ivan1767p** [comment]
> @nekrasovweb @ivan1767p can u test this in version 4.10.1, ive run locally but couldnt get those to work. maybe something went wrong with some merge conflicts.

Need more details

**Comment by ivan1767p** [comment]
@jmecosta You merge https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/pull/70 right? Why did you do that? You break my code.

**Comment by jmecosta** [comment]
Make sure u are in latest master, I had to force push since there was a
older pull request that was behind and I had to solve a few merge
conflicts.

What kind of failure? Compilation or runtime? It was compiling at least for
me

**Comment by ivan1767p** [comment]
@jmecosta , https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/pull/75

**Pull request merged**
