### PR TITLE
Enable the PR Hook to trigger a "shadow merge"

### PR DESCRIPTION
**Pull request by dzwicker**
A "shadow merge" is a pre merge of the pr branch to the actual taget branch. To build this branch is a really powerfull feature.

I have adjusted the definition of the build pull request property as the name was misleading.

### CODE REVIEW

**Comment by jmecosta** [comment]
Whats the condition then to finnaly merge this pre merge branch and who
does it, is the pull request page supporting this feature?

I understand the concept, u want to test your changes against the target
branch before merging... just dont understand who or what actually merges it

**Comment by jmecosta** [comment]
For the pull request trigger u extended it so that u can

1. Trigger only there is a pull request (existing)
2. Trigger when there is pull request on top of normal trigger without pull
request

For the second does the hook now does 2 triggers when we push if we have a
pull request open.

**Comment by dzwicker** [comment]
> Whats the condition then to finnaly merge this pre merge branch and who does it, is the pull request page supporting this feature? I understand the concept, u want to test your changes against the target branch before merging... just dont understand who or what actually merges it

The pre merge branch is created by bitbucket for every pr. So for every pr there are foure branches involved:

1. refs/heads/feature/xxxx (source)
2. refs/heads/<target> (e.g. refs/heads/master)
3. refs/pull-request/<id>/from (= source)
4. refs/pull-request/<id>/merge (pre merge of source into target)

Bitbucket manages 3+4 in the background. No user interaction is needed. Bitbucket updates these branches if needed before fire any pr-events.

Without additional (plugins|https://marketplace.atlassian.com/apps/1218706/shadow-merge-commit-build-status?hosting=server&tab=overview) the pr page doesn't show information about this branch (except if there are merge conflicts, than you see a "magic" message indicating the refs/pull-request/<id>/merge branch fails), but it exists in the background.

**Comment by dzwicker** [comment]
> For the second does the hook now does 2 triggers when we push if we have a pull request open.

1. I have rework the `postUpdate` to trigger all the time except for `onlyTriggerOnPullRequest`. This is something new and changes the behavior of the `triggerOnPullRequest` property (before the trigger only fire iff a pr exists). 
2. The `TeamcityPullrequestEventListener` can now fire two events:
2.1. `Trigger the source branch` is only emitted if `triggerOnPullRequest` and `onlyTriggerOnPullRequest` are both enabled as 1. is disabled in this case.
2.2. `Trigger the shadow merge branch` is only emitted if `triggerOnPullRequest` and `triggerPullRequestShadowMerge` are both enabled.

So hopefully the source branch is only triggered once even if a pr exists.

**Comment by dzwicker** [comment]
> 1. This is something new and changes the behavior of the `triggerOnPullRequest` property (before the trigger only fire iff a pr exists).

This is something should stated in the docs. And perhaps should trigger a new main version 5.x.x?

**Comment by jmecosta** [comment]
Yep now makes total sense... thanks for the clarification

**Comment by jmecosta** [comment]
Yes, for that reason would you be ok to split the these  changes in 2 pull
requests since they are functionally different and easier to reciew and test

**Comment by jmecosta** [comment]
@dzwicker thanks for the patch, it will be avaialble in 4.10.1. If you could test it, since i had to solve quite a few merge conflicts... ive tested our featuers and they work.

**Comment by dzwicker** [comment]
sorry. out bitbucket is a 6.x

**Pull request merged**
