### PR TITLE
Feature/external config

### PR DESCRIPTION
**Pull request by jmecosta**

### CODE REVIEW

**Comment by jmecosta** [comment]
@auriusbendikas this should cover our use case. so not everything is connect and we should keep this baseline for the new release. so all changes you want to change please try to keep what it exists there.

later, if you dont have time, i cant try to organize the configuration of the hook to make it a bit more pretty

**Comment by auriusbendikas** [comment]
@jmecosta looks good!

**Comment by jmecosta** [comment]
@auriusbendikas ive change the configuration according with what i said

image

So now it should be possibile to had more options if needed. Ive also fix the pull request option and it working. If you dont have time to adjust the normal trigger part, i can fix that. And we can then release a new version.

for the configuration dialog, ive mixed a bit of html with soy templates, simple because in Atlasian documentation they also do it. I dont have time to do a investigation on soy templates (i dont want also).

**Comment by auriusbendikas** [comment]
@jmecosta Looks good. I would like to branch out from it to start my backed development :) Please merge it when ready.

**Comment by jmecosta** [comment]
Ok i a bit i will do it. Do you still want me to move the main hook code to
the new regx config. So that the hook is totally working. Or do you want to
do it?

**Comment by auriusbendikas** [comment]
@jmecosta 

It is up to you. One thing I would like to improve is implementation of TeamcityConnector.java and TeamctiyRest.java. But if you want me to do something else I will be happy to help.

**Comment by jmecosta** [comment]
ok, so let me then adjust the hook code. Since the rest thing you want is a bit out of scope of the configuration change. i will merge when ready

**Pull request merged**
