### PR TITLE
Fix triggering empty branches and fix stacktrace logging

### LINKED ISSUE #43: Push new branch to bitbucket does not trigger a build
If a branch is created locally and pushed to bitbucket it seams not to trigger teamcity. Even with some local commits and pushing to server no trigger fires.

If i do a 'ammend commit' after pushing the new branch (and push this new ammended commit) teamcity starts a new build

### PR DESCRIPTION
**Pull request by solazs**
PR to fix #43 
I've added an if condition to avoid trying to look for changed files on an empty branch (no point, since on an empty branch, it makes no sense to look for included or excluded paths since there is no change)

I've also added a new method to properly log stack traces if debug is on.

There are some whitespace changes, sorry for that, I did not want to bother with reverting them after my IDE corrected them.

### CODE REVIEW

**Comment by solazs** [comment]
Hey, is there any ETA for a release incorporating this change?

**Comment by solazs** [comment]
@jmecosta

Hey, is there any ETA for a release incorporating this change?

**Comment by jmecosta** [comment]
Today? Tought you would be ok with using own local build 😉

**Comment by jmecosta** [comment]
done

**Comment by solazs** [comment]
I am, but custom stuff is generally discouraged here, due to support requirements. 
Thank you for the quick reply!

**Pull request merged**
