### PR TITLE
Close BufferedReader and InputStream

### PR DESCRIPTION
**Pull request by ivan1767p**
Close BufferedReader and InputStream.

### CODE REVIEW

**Comment by ivan1767p** [comment]
@jmecosta, hi. Please merge and make release build.

**Comment by ivan1767p** [comment]
@jmecosta can you make build for https://marketplace.atlassian.com/apps/1215178/teamcity-remote-trigger-hook/ ? Thanks in advance!

**Comment by jmecosta** [comment]
https://marketplace.atlassian.com/manage/apps/1215178/versions/300000290/details

**Comment by ivan1767p** [comment]
Thanks a lot!

**Comment by jmecosta** [comment]
welcome

**Pull request merged**
