### PR TITLE
Close stream for Http methods

### PR DESCRIPTION
**Pull request by ivan1767p**
Close stream for Http methods

### CODE REVIEW

**Comment by ivan1767p** [comment]
I reformat code(codestyle). For pretty read.

**Comment by jmecosta** [comment]
Later today, thanks

**Comment by timlok** [comment]
@jmecosta Hello. We are very much looking forward to the merger. )

**Comment by delcom610** [comment]
@jmecosta Hey, I need this merge so much, thanks!

**Comment by jmecosta** [comment]
Damn thanks for reminding. Will be done in a bit. Thanks

**Comment by jmecosta** [comment]
now done, sorry for the delay. and thanks for contribution

**Pull request merged**
